const express=require('express');
const Router=express.Router();
const passport=require('../config/passport-google-oauth2-strategy');
const contentController=require('../controllers/content');
Router.use('/announcements',require('./announcements'));
Router.get('/studymaterial',contentController.studyMaterial);
Router.get('/recordedlectures',contentController.recordedLectures);
Router.get('/assignments',contentController.assignments);
Router.get('/timetable',contentController.timeTable);
Router.get('/doubts',contentController.doubts);
module.exports=Router;